### ISSUE TITLE
dependency animated_box_decoration-0.0.6 fails in Xcloud workflow

### ISSUE THREAD

**Issue by jakusb** [KevinVan720/morphable_shape#11]
/Users/local/.pub-cache/hosted/pub.dev/animated_box_decoration-0.0.6/lib/src/box_decoration_mix.dart:220:27: Error: The return type of the method 'BoxDecorationMix.padding' is 'EdgeInsetsGeometry?', which does not match the return type, 'EdgeInsetsGeometry', of the overridden method, 'Decoration.padding'.

**Comment by jakusb** [comment]
@KevinVan720 : Please review and merg my pull request in animated_box_decoration project, so you can then use that new version for this project. My builds are now failing, so some speed would be much appreciated ;)

**Comment by KevinVan720** [comment]
Hi @jakusb. The package has been updated now.

**Comment by jakusb** [comment]
I will test it now and confirm if all is working again.

**Comment by jakusb** [comment]
@KevinVan720 : I can confirm the issue is now resolved! Thanks for the quick response!
