### ISSUE TITLE
Error Since Upgrade Flutter

### ISSUE THREAD

**Issue by yelkamel** [KevinVan720/morphable_shape#13]
Error (Xcode): ../../.pub-cache/hosted/pub.dev/morphable_shape-1.6.6/lib/src/shape_borders/rectangle.dart:254:23: Error: The method 'hashValues' isn't defined for the class 'RectangleShapeBorder'.

Could not build the application for the simulator.

**Comment by smj1234** [comment]
you need to create custom package and change it for new flutter

**Comment by te8uekm12** [comment]
Could you help me with it?

**Comment by KevinVan720** [comment]
I have published a new version which should resolve the issue. Thank you!
