### ISSUE TITLE
The method 'Length' isn't defined

### ISSUE THREAD

**Issue by Spooky12** [KevinVan720/morphable_shape#3]
Hi,

I just updated `morphable_shape` from version 1.4.5 to 1.4.8 and I have this error:

```
The method 'Length' isn't defined for the type 'HexIcon'.
Try correcting the name to the name of an existing method, or defining a method named 'Length'.
```

 It seems that `Length`/`Dimension` required by `cornerRadius` type in `PolygonShapeBorder` are not exported by the lib anymore.

___
My code :

```dart
import 'package:flutter/material.dart';
import 'package:morphable_shape/morphable_shape.dart';

class HexIcon extends StatelessWidget {
  final Widget icon;
  final Color backgroundColor;

  const HexIcon({
    @required this.icon,
    this.backgroundColor = Colors.white,
    Key key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Ink(
      decoration: ShapeDecoration(
        shape: PolygonShapeBorder(
          sides: 6,
          cornerRadius: Length(8), // <-- Error here with morphable_shape 1.4.8
        ),
        color: backgroundColor,
      ),
      child: Padding(padding: const EdgeInsets.all(15.0), child: icon),
    );
  }
}
```

**Comment by KevinVan720** [comment]
Hi. Could you try to include the dimension package and see if this issue is resolved? This package is also developed by me. I factored it out a while ago.

**Comment by Spooky12** [comment]
It works when I include the dimension package, but I think the package should export dimension package (or at least the classes from dimension required by morphable_shape) to avoid potential dependencies issues and to avoid having to add a second package to pubspec.yaml to make the first one work.

Like flutter_bloc package that exports bloc package and some classes from provider package.

**Comment by KevinVan720** [comment]
I see. I agree with you. I'll fix this shortly.
