### ISSUE TITLE
Incorrect LICENSE

### ISSUE THREAD

**Issue by Zabadam** [KevinVan720/morphable_shape#4]
Correct me if I am wrong, but I was flipping through some licenses on a generated Flutter license page, and both this and `animated_styled_widget` have "Remi Rousselet" listed as the owner in the license file.

**Comment by KevinVan720** [comment]
😂You are right. The license is a copy from another package. I'll correct
it. Thanks!

Zabadam ***@***.***> 于2021年5月6日周四 上午6:17写道：
