### ISSUE TITLE
Serialisation 

### ISSUE THREAD

**Issue by Seferi** [KevinVan720/morphable_shape#6]
Hi, I created a shape in fluttershape.com and trying to deserialise in my app as it's mentioned in the documentation.

<img width="695" alt="Screen Shot 2022-09-05 at 13 09 02 PM" src="https://user-images.githubusercontent.com/2592842/188435490-cc19d6b5-be04-4678-b60b-49f099723a8a.png">

`Shape shapeDecoded = parseShape(json.decode(jsonFromFlutterShape.com));`

But there is no Shape type nor a parseShape method when I try to parse the json. I appreciate if you could help. Thanks in advance.

**Comment by KevinVan720** [comment]
Hi. Nice shape design! 

You should use this function: MorphableShapeBorder? parseMorphableShapeBorder(Map<String, dynamic>? map). Sorry I forgot to update the documentation.

**Comment by Seferi** [comment]
Thanks mate. Awesome package you got here! Extremely helpful! 

 But I can't use MorphableShapeDesign in Container(decoration: ShapeDecoration(shape: parseMorphableShapeBorder())) nor in ClipPath . How can I get my container in to this shape ?

**Comment by KevinVan720** [comment]
Thanks. Yes, the package is not really compatible with Container right now. You should use DecoratedShadowedShape instead (and AnimatedDecoratedShadowedShape if you want implicit animation). You get inner shadow support as a bonus. 

I am considering adding support for the Container/ClipPath.  But it might require significant refactoring.

**Comment by Seferi** [comment]
Actually I'm not gonna animate it at all. I just need a container in this shape, and another one, same but flipped..

**Comment by KevinVan720** [comment]
I see. I assume you are trying to create a chat app. The DecoratedShadowedShape should still suit your need.

**Comment by Seferi** [comment]
Thanks for your help mate!
