### ISSUE TITLE
Failed assertion:  'outer.nodes.length == fillColors.length': is not true

### ISSUE THREAD

**Issue by mikairyuu** [KevinVan720/morphable_shape#7]
Even a basic example from the docs throws the following error
`
package:morphable_shape/src/dynamic_path/border_paths.dart: Failed assertion: line 26 pos 12:'outer.nodes.length == fillColors.length': is not true.
`
Code from the docs I used:
`
Container(
      width: 100,
      height: 100,
      decoration: ShapeDecoration(
          shape: RoundedRectangleShapeBorder(
        borderRadius:
            DynamicBorderRadius.all(DynamicRadius.circular(Length(100))),
        borderSides: RectangleBorderSides.all(DynamicBorderSide.none),
      )),
    )
`
Flutter version used is 3.7.0
Package is 1.6.4

**Comment by KevinVan720** [comment]
Will look into this by the end of this week!

**Comment by KevinVan720** [comment]
Hi @mikairyuu. I remember there was some problem with putting a `MorphableShapeBorder` inside of a `Container`. I suggest you try the `DecoratedShadowedShape` widget. I am considering refactoring this package to make it work 100% with the standard Flutter widgets, but that might take quite a while.
