### ISSUE TITLE
Update image version to v4.0.10

### ISSUE THREAD

**Issue by ShvetsovZE** [KevinVan720/morphable_shape#8]
Package throws dependency resolution exception during the build when used with flutter_native_splash as it was recently updated to image tp v4.0.10. 
[flutter_native_splash  change log](https://pub.dev/packages/flutter_native_splash/changelog)
Should be resolved by referencing new version of  [animated_box_decoration](https://pub.dev/packages/animated_box_decoration) produced by fix of [this issue](https://github.com/KevinVan720/animated_box_decoration/issues/1)

**Comment by ShvetsovZE** [comment]
@KevinVan720 I've created a [PR](https://github.com/KevinVan720/morphable_shape/pull/9)for this issue, but unfortunately can't link it

**Comment by KevinVan720** [comment]
I have just updated that dependency. Thank you.

**Comment by ShvetsovZE** [comment]
Thank you @KevinVan720 , i think the issue can be closed
